
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  role_hierarchy:
    ########### DASHBOARD ROLES ###################
    ROLE_ACCESS_DASHBOARD: [ ROLE_USER ]
    ########### SETTING ROLES ###################
    ROLE_ACCESS_SETTING: [ ROLE_USER ]
    ########### APPLICATION ROLES ###################
    ROLE_APPLICATION_INDEX: [ ROLE_USER ]
    ROLE_APPLICATION_DETAIL: [ ROLE_USER ]
    ROLE_APPLICATION_NEW: [ ROLE_USER ]
    ROLE_APPLICATION_EDIT: [ ROLE_USER ]
    ROLE_APPLICATION_DELETE: [ ROLE_USER ]
    ROLE_APPLICATION_ALL:
      - ROLE_APPLICATION_INDEX
      - ROLE_APPLICATION_DETAIL
      - ROLE_APPLICATION_NEW
      - ROLE_APPLICATION_EDIT
      - ROLE_APPLICATION_DELETE
    ########### APPLICATION_GROUP ROLES ###################
    ROLE_APPLICATION_GROUP_INDEX: [ ROLE_USER ]
    ROLE_APPLICATION_GROUP_DETAIL: [ ROLE_USER ]
    ROLE_APPLICATION_GROUP_NEW: [ ROLE_USER ]
    ROLE_APPLICATION_GROUP_EDIT: [ ROLE_USER ]
    ROLE_APPLICATION_GROUP_DELETE: [ ROLE_USER ]
    ROLE_APPLICATION_GROUP_ALL:
      - ROLE_APPLICATION_GROUP_INDEX
      - ROLE_APPLICATION_GROUP_DETAIL
      - ROLE_APPLICATION_GROUP_NEW
      - ROLE_APPLICATION_GROUP_EDIT
      - ROLE_APPLICATION_GROUP_DELETE
    ROLE_APPLICATION_GROUP_INDEX_NOT_NEW: [ ROLE_USER ]
    ########### APPLICATION_IMPORT ROLES ###################
    ROLE_APPLICATION_IMPORT_INDEX: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_DETAIL: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_NEW: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_EDIT: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_DELETE: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_DOWNLOAD: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_ALL:
      - ROLE_APPLICATION_IMPORT_INDEX
      - ROLE_APPLICATION_IMPORT_DETAIL
      - ROLE_APPLICATION_IMPORT_NEW
      - ROLE_APPLICATION_IMPORT_EDIT
      - ROLE_APPLICATION_IMPORT_DELETE
      - ROLE_APPLICATION_IMPORT_DOWNLOAD
    ########### APPLICATION_IMPORT_TEMPLATE CODE ROLES ###################
    ROLE_APPLICATION_IMPORT_TEMPLATE_INDEX: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_TEMPLATE_DETAIL: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_TEMPLATE_NEW: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_TEMPLATE_EDIT: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_TEMPLATE_DELETE: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_TEMPLATE_DOWNLOAD: [ ROLE_USER ]
    ROLE_APPLICATION_IMPORT_TEMPLATE_ALL:
      - ROLE_APPLICATION_IMPORT_TEMPLATE_INDEX
      - ROLE_APPLICATION_IMPORT_TEMPLATE_DETAIL
      - ROLE_APPLICATION_IMPORT_TEMPLATE_NEW
      - ROLE_APPLICATION_IMPORT_TEMPLATE_EDIT
      - ROLE_APPLICATION_IMPORT_TEMPLATE_DELETE
      - ROLE_APPLICATION_IMPORT_TEMPLATE_DOWNLOAD
    ROLE_APPLICATION_IMPORT_MENU_ITEM: [ ROLE_USER ]
    ########### ATECO_CODE ROLES ###################
    ROLE_ATECO_CODE_INDEX: [ ROLE_USER ]
    ROLE_ATECO_CODE_DETAIL: [ ROLE_USER ]
    ROLE_ATECO_CODE_NEW: [ ROLE_USER ]
    ROLE_ATECO_CODE_EDIT: [ ROLE_USER ]
    ROLE_ATECO_CODE_DELETE: [ ROLE_USER ]
    ROLE_ATECO_CODE_ALL:
      - ROLE_ATECO_CODE_INDEX
      - ROLE_ATECO_CODE_DETAIL
      - ROLE_ATECO_CODE_NEW
      - ROLE_ATECO_CODE_EDIT
      - ROLE_ATECO_CODE_DELETE
    ########### BANK ROLES ###################
    ROLE_BANK_INDEX: [ ROLE_USER ]
    ROLE_BANK_DETAIL: [ ROLE_USER ]
    ROLE_BANK_NEW: [ ROLE_USER ]
    ROLE_BANK_EDIT: [ ROLE_USER ]
    ROLE_BANK_DELETE: [ ROLE_USER ]
    ROLE_BANK_ALL:
      - ROLE_BANK_INDEX
      - ROLE_BANK_DETAIL
      - ROLE_BANK_NEW
      - ROLE_BANK_EDIT
      - ROLE_BANK_DELETE
    ########### BANK_LEASING ROLES ###################
    ROLE_BANK_LEASING_INDEX: [ ROLE_USER ]
    ROLE_BANK_LEASING_DETAIL: [ ROLE_USER ]
    ROLE_BANK_LEASING_NEW: [ ROLE_USER ]
    ROLE_BANK_LEASING_EDIT: [ ROLE_USER ]
    ROLE_BANK_LEASING_DELETE: [ ROLE_USER ]
    ROLE_BANK_LEASING_ALL:
      - ROLE_BANK_LEASING_INDEX
      - ROLE_BANK_LEASING_DETAIL
      - ROLE_BANK_LEASING_NEW
      - ROLE_BANK_LEASING_EDIT
      - ROLE_BANK_LEASING_DELETE
    ########### CONFIDI ROLES ###################
    ROLE_CONFIDI_INDEX: [ ROLE_USER ]
    ROLE_CONFIDI_DETAIL: [ ROLE_USER ]
    ROLE_CONFIDI_NEW: [ ROLE_USER ]
    ROLE_CONFIDI_EDIT: [ ROLE_USER ]
    ROLE_CONFIDI_DELETE: [ ROLE_USER ]
    ROLE_CONFIDI_ALL:
      - ROLE_CONFIDI_INDEX
      - ROLE_CONFIDI_DETAIL
      - ROLE_CONFIDI_NEW
      - ROLE_CONFIDI_EDIT
      - ROLE_CONFIDI_DELETE
    ########### REPORT ROLES ###################
    ROLE_REPORT_INDEX: [ ROLE_USER ]
    ROLE_REPORT_DETAIL: [ ROLE_USER ]
    ROLE_REPORT_NEW: [ ROLE_USER ]
    ROLE_REPORT_EDIT: [ ROLE_USER ]
    ROLE_REPORT_DELETE: [ ROLE_USER ]
    ROLE_REPORT_DOWNLOAD: [ ROLE_USER ]
    ROLE_REPORT_ALL:
      - ROLE_REPORT_INDEX
      - ROLE_REPORT_DETAIL
      - ROLE_REPORT_NEW
      - ROLE_REPORT_EDIT
      - ROLE_REPORT_DELETE
      - ROLE_REPORT_DOWNLOAD
    ########### MANAGE_USER ROLES ###################
    ROLE_MANAGE_USER_INDEX: [ ROLE_USER ]
    ROLE_MANAGE_USER_DETAIL: [ ROLE_USER ]
    ROLE_MANAGE_USER_NEW: [ ROLE_USER ]
    ROLE_MANAGE_USER_EDIT: [ ROLE_USER ]
    ROLE_MANAGE_USER_DELETE: [ ROLE_USER ]
    ROLE_MANAGE_USER_ALL:
      - ROLE_MANAGE_USER_INDEX
      - ROLE_MANAGE_USER_DETAIL
      - ROLE_MANAGE_USER_NEW
      - ROLE_MANAGE_USER_EDIT
      - ROLE_MANAGE_USER_DELETE
    ########### ASSIGNABLE ROLES ###################
    ROLE_OPERATORE_CONFIDI:
      - ROLE_APPLICATION_ALL
      - ROLE_APPLICATION_GROUP_ALL
      - ROLE_APPLICATION_IMPORT_ALL
      - ROLE_APPLICATION_IMPORT_MENU_ITEM
      - ROLE_ACCESS_DASHBOARD
    ROLE_OPERATORE_ARTIGIANCASSA:
      - ROLE_APPLICATION_GROUP_ALL
      - ROLE_APPLICATION_ALL
      - ROLE_REPORT_ALL
      - ROLE_ACCESS_DASHBOARD
    ROLE_OPERATORE_REGIONE:
      - ROLE_APPLICATION_GROUP_INDEX
      - ROLE_APPLICATION_GROUP_INDEX_NOT_NEW
      - ROLE_APPLICATION_GROUP_DETAIL
      - ROLE_CONFIDI_INDEX
      - ROLE_CONFIDI_DETAIL
      - ROLE_ACCESS_DASHBOARD
      - ROLE_REPORT_INDEX
      - ROLE_REPORT_DOWNLOAD
      - ROLE_ACCESS_SETTING
    ROLE_ADMIN_SECURITY:
      - ROLE_MANAGE_USER_ALL
      - ROLE_ACCESS_SETTING
    ROLE_ADMIN:
      - ROLE_ATECO_CODE_ALL
      - ROLE_BANK_ALL
      - ROLE_BANK_LEASING_ALL
      - ROLE_CONFIDI_ALL
      - ROLE_APPLICATION_IMPORT_MENU_ITEM
      - ROLE_APPLICATION_IMPORT_TEMPLATE_ALL
      - ROLE_ACCESS_SETTING
    ROLE_SUPER_ADMIN:
      - ROLE_APPLICATION_ALL
      - ROLE_APPLICATION_GROUP_ALL
      - ROLE_APPLICATION_IMPORT_ALL
      - ROLE_APPLICATION_IMPORT_TEMPLATE_ALL
      - ROLE_APPLICATION_IMPORT_MENU_ITEM
      - ROLE_ATECO_CODE_ALL
      - ROLE_BANK_ALL
      - ROLE_BANK_LEASING_ALL
      - ROLE_CONFIDI_ALL
      - ROLE_REPORT_ALL
      - ROLE_MANAGE_USER_ALL
      - ROLE_ACCESS_DASHBOARD
      - ROLE_ACCESS_SETTING

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # PKCE routes - NO authentication required
    pkce:
      pattern: ^/pkce
      security: false

    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker

      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
        password_parameter: password

      two_factor:
        auth_form_path: 2fa_login
        check_path: 2fa_login_check

      logout:
        path: app_logout

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/elbHealthCheck, roles: PUBLIC_ACCESS }
    - { path: ^/getDataFromNsia, roles: PUBLIC_ACCESS }
    - { path: ^/parseDataNsia, roles: PUBLIC_ACCESS }
    - { path: ^/sendDataToNsia, roles: PUBLIC_ACCESS }
    - { path: ^/sendSyncLogToS3, roles: PUBLIC_ACCESS }
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/login-check, roles: PUBLIC_ACCESS }
    - { path: ^/pkce, roles: PUBLIC_ACCESS }
    - { path: ^/logout, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }
    - { path: ^/update-password, roles: PUBLIC_ACCESS }
    - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
    - { path: ^/, roles: ROLE_USER }
